[libraries]
annotations = "org.jetbrains:annotations:24.0.1"
dokkaKotlinAsJavaPlugin = "org.jetbrains.dokka:kotlin-as-java-plugin:1.9.0"
dokkaVersioningPlugin = "org.jetbrains.dokka:versioning-plugin:1.9.0"
dokkaBase = "org.jetbrains.dokka:dokka-base:1.9.0"
imageio = "com.twelvemonkeys.imageio:imageio-core:3.9.4"
imageio-batik = "com.twelvemonkeys.imageio:imageio-batik:3.9.4"
batik= "org.apache.xmlgraphics:batik-all:1.17"
[plugins]
style = "org.sourcegrade.style:3.0.0"
dokka = "org.jetbrains.dokka:1.9.0"

