[versions]
dokka = "1.9.10"

[libraries]
annotations = "org.jetbrains:annotations:24.1.0"
dokkaKotlinAsJavaPlugin = { module = "org.jetbrains.dokka:kotlin-as-java-plugin", version.ref = "dokka" }
dokkaVersioningPlugin = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }
dokkaBase = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
imageio-batik = "com.twelvemonkeys.imageio:imageio-batik:3.9.4"
batik = "org.apache.xmlgraphics:batik-all:1.17"

[plugins]
kotlin-jvm = "org.jetbrains.kotlin.jvm:1.9.10"
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
style = "org.sourcegrade.style:3.0.0"
