[libraries]
annotations = "org.jetbrains:annotations:24.0.1"
dokkaKotlinAsJavaPlugin = "org.jetbrains.dokka:kotlin-as-java-plugin:1.8.20"
dokkaVersioningPlugin = "org.jetbrains.dokka:versioning-plugin:1.8.20"
dokkaBase = "org.jetbrains.dokka:dokka-base:1.8.20"
[plugins]
style = "org.sourcegrade.style:3.0.0"
dokka = "org.jetbrains.dokka:1.8.20"

